FROM node:20-alpine

# Tạo thư mục làm việc
WORKDIR /usr/src/frontend

# Copy file package và lock trước
COPY package*.json yarn.lock* ./

# Cài dependencies
RUN yarn install --frozen-lockfile

# Copy source code
COPY . .

# Mở port của Vite (mặc định 5173)
EXPOSE 5173

# Chạy Vite dev server
CMD ["yarn", "dev", "--host"]